version: "3.6"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        container_name: elasticsearch
        environment:
            node.name: elasticsearch
            ES_JAVA_OPTS: "-Xmx512m -Xms512m"
            ELASTIC_USERNAME: elastic
            ELASTIC_PASSWORD: changeme
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elastic-net
        volumes:
#            - type: bind
#              source: "./elasticsearch/config/elasticsearch.yml"
#              target: /usr/share/elasticsearch/config/elasticsearch.yml
            - type: bind
              source: ./docker/data
              target: /usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.4
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - elastic-net
        volumes:
            - type: bind
              source: ./docker/kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
        depends_on:
            - elasticsearch
networks:
    elastic-net:
        driver: bridge
