name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:    
    runs-on: self-hosted      
    steps:
    - uses: actions/checkout@v3    
    - run: |              
        echo "Another message or command"
        whoami
        pwd
        ls -l /home/g1admin/g1-elastaler
        cd /home/g1admin/g1-elastaler
        git pull
    - run: echo "One last message"
